import test from "node:test";
import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { once } from "node:events";
import { readFile } from "node:fs/promises";
import { chromium } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { PrismaClient } from "../../src/generated/prisma/client.ts";
import { PrismaPg } from "@prisma/adapter-pg";
import { workspaceTestTarget } from "../../scripts/workspace-test-target.mjs";
import { createWorkspaceService } from "../../src/lib/workspaces/service.mjs";
import { snapshotTemplate } from "../../src/lib/templates/catalog.mjs";
import { startFixtureServer, signedCookie } from "../support/http-fixture.mjs";

const target = workspaceTestTarget(process.env.WORKSPACE_TEST_DATABASE_URL);
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: target }) });
const service = createWorkspaceService(db);
const base = "http://127.0.0.1:3100";

test("authenticated two-destination shell uses real workspace data", async (t) => {
  const userId = `fixture-${randomUUID()}`;
  const otherUserId = `fixture-${randomUUID()}`;
  let server, browser;
  t.after(async () => {
    await browser?.close();
    if (server?.exitCode === null) { server.kill("SIGTERM"); await once(server, "exit"); }
    await db.waitList.deleteMany({ where: { userId } });
    await db.waitList.deleteMany({ where: { userId: otherUserId } });
    await db.workspace.deleteMany({ where: { members: { some: { userId } } } });
    await db.workspace.deleteMany({ where: { members: { some: { userId: otherUserId } } } });
    await db.user.deleteMany({ where: { id: { in: [userId, otherUserId] } } });
    await db.$disconnect();
  });
  await db.user.create({ data: { id: userId, email: `${userId}@example.invalid`, name: "Shell fixture" } });
  const token = randomUUID();
  await db.session.create({ data: { id: randomUUID(), token, userId, expiresAt: new Date(Date.now() + 120000) } });
  const personal = await service.ensurePersonal(userId);
  const waitlist = await db.waitList.create({ data: { userId, workspaceId: personal.id, name: "First launch", description: "Real fixture content" } });
  await db.user.create({ data: { id: otherUserId, email: `${otherUserId}@example.invalid` } });
  const otherWorkspace = await service.ensurePersonal(otherUserId);
  await db.waitList.create({ data: { userId: otherUserId, workspaceId: otherWorkspace.id, name: "First launch external" } });
  server = await startFixtureServer();
  browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const cookie = signedCookie(token).split("=");
  await context.addCookies([{ name: cookie[0], value: cookie[1], domain: "127.0.0.1", path: "/", httpOnly: true, sameSite: "Lax" }]);
  const page = await context.newPage();
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await t.test("dashboard redirects and navigation has exactly two real destinations", async () => {
    await page.goto(`${base}/dashboard`);
    assert.ok(page.url().endsWith("/wait-lists"));
    assert.deepEqual(await page.getByRole("navigation", { name: "Main navigation" }).getByRole("link").allTextContents(), ["Waitlists", "Settings"]);
    assert.equal(await page.locator("aside").count(), 0);
    assert.equal(await page.getByRole("row", { name: /First launch/ }).count(), 1);
    assert.equal(await page.getByLabel("Workspace", { exact: true }).count(), 0);
  });
  await t.test("profile saves on the real account and settings passes axe", async () => {
    await page.getByRole("link", { name: "Settings", exact: true }).click();
    await page.getByLabel("Display name").fill("Updated fixture");
    await page.getByRole("button", { name: "Save profile" }).click();
    await page.getByRole("status").filter({ hasText: "Profile saved." }).waitFor();
    assert.equal((await db.user.findUnique({ where: { id: userId } })).name, "Updated fixture");
    await page.reload();
    assert.equal(await page.getByLabel("Display name").inputValue(), "Updated fixture");
    await page.getByLabel("Display name").fill("   ");
    await page.getByRole("button", { name: "Save profile" }).click();
    await page.getByRole("alert").filter({ hasText: "Enter a name" }).waitFor();
    assert.equal(await page.getByLabel("Display name").inputValue(), "   ");
    await page.getByLabel("Display name").fill("Updated fixture");
    assert.deepEqual((await new AxeBuilder({ page }).include(".product-shell").analyze()).violations, []);
  });
  await t.test("developer settings creates a waitlist-bound key once and lists only safe metadata", async () => {
    await page.getByRole("link", { name: "Developers", exact: true }).click();
    await page.getByRole("heading", { name: "Developers", exact: true }).waitFor();
    await page.getByRole("button", { name: "Create API Key" }).click();
    const dialog = page.getByRole("dialog");
    await dialog.getByLabel("API key name").fill("Launch signup form");
    await dialog.getByRole("combobox").nth(0).click();
    await page.getByRole("option", { name: "First launch" }).click();
    await dialog.getByRole("combobox").nth(1).click();
    await page.getByRole("option", { name: "In 30 days" }).click();
    const createResponse = page.waitForResponse((response) => response.url().includes("/api/v1/api-keys/create-and-link") && response.request().method() === "POST");
    await dialog.getByRole("button", { name: "Create & Link API Key" }).click();
    const response = await createResponse;
    assert.equal(response.status(), 200);
    const created = (await response.json()).data.apiKey;
    assert.match(created.apiKey, /^wl2_[a-f0-9]{32}_[A-Za-z0-9_-]{43}$/);
    assert.equal(Object.hasOwn(created, "keyHash"), false);
    const stored = await db.apiKey.findUnique({ where: { id: created.id } });
    assert.equal(stored.waitlistId, waitlist.id);
    assert.deepEqual(stored.scopes, ["waitlist:write"]);
    const [, secret] = created.apiKey.match(/^wl2_[a-f0-9]{32}_([A-Za-z0-9_-]{43})$/);
    assert.equal(stored.keyHash, createHash("sha256").update(secret).digest("hex"));
    assert.ok(stored.expiresAt > new Date(Date.now() + 25 * 24 * 60 * 60 * 1000));
    const listed = await page.request.get(`${base}/api/v1/api-keys`);
    const listedKey = (await listed.json()).data.find((key) => key.id === created.id);
    assert.ok(listedKey);
    assert.equal(Object.hasOwn(listedKey, "keyHash"), false);
    assert.equal(listedKey.key, "••••••••••••••••");
    await dialog.getByRole("button", { name: "Done" }).click();
    assert.deepEqual((await new AxeBuilder({ page }).include(".product-settings-panel").analyze()).violations, []);
  });
  await t.test("waitlist referral sharing saves and stays inside its settings", async () => {
    await page.goto(`${base}/wait-lists/${waitlist.id}/settings`);
    const referralControl = page.getByRole("checkbox", { name: /Enable referral sharing/ });
    assert.equal(await referralControl.isChecked(), true);
    await referralControl.setChecked(false);
    await page.getByRole("status").filter({ hasText: "Referral sharing is off." }).waitFor();
    assert.equal((await db.waitList.findUnique({ where: { id: waitlist.id } })).showReferrals, false);
    await referralControl.setChecked(true);
    await page.getByRole("status").filter({ hasText: "Referral sharing is on." }).waitFor();
    assert.equal((await db.waitList.findUnique({ where: { id: waitlist.id } })).showReferrals, true);
    assert.deepEqual((await new AxeBuilder({ page }).include(".product-settings-panel").analyze()).violations, []);
  });
  await t.test("analytics endpoint is authorized and returns aggregate-only data", async () => {
    const response = await page.request.get(`${base}/api/wait-lists/${waitlist.id}/analytics?days=7&timeZone=America%2FLos_Angeles`);
    assert.equal(response.status(), 200);
    const analytics = await response.json();
    assert.equal(analytics.range.days, 7);
    assert.equal(analytics.range.timeZone, "America/Los_Angeles");
    assert.match(analytics.range.startDate, /^\d{4}-\d{2}-\d{2}$/);
    assert.match(analytics.range.endDate, /^\d{4}-\d{2}-\d{2}$/);
    assert.equal(analytics.series.length, 7);
    assert.equal(analytics.summary.signups, 0);
    assert.equal(analytics.summary.visitors, 0);
    assert.equal(response.headers()["cache-control"], "private, no-store");
    assert.equal(Object.hasOwn(analytics, "signups"), false);
    assert.doesNotMatch(JSON.stringify(analytics), /[^\s"@]+@[^\s"@]+\.[^\s"@]+/);
    assert.equal(Object.hasOwn(analytics.summary, "email"), false);
    assert.equal(Object.hasOwn(analytics.series[0], "email"), false);
    const invalid = await page.request.get(`${base}/api/wait-lists/${waitlist.id}/analytics?days=8`);
    assert.equal(invalid.status(), 400);
    const inaccessible = await page.request.get(`${base}/api/wait-lists/not-a-waitlist/analytics?days=7`);
    assert.equal(inaccessible.status(), 404);
    const anonymousContext = await browser.newContext();
    try {
      const anonymousPage = await anonymousContext.newPage();
      const unauthenticated = await anonymousPage.request.get(`${base}/api/wait-lists/${waitlist.id}/analytics?days=7`);
      assert.equal(unauthenticated.status(), 401);
    } finally {
      await anonymousContext.close();
    }
  });
  await t.test("waitlist overview renders real analytics and an accessible table across themes and widths", async () => {
    await db.waitList.update({ where: { id: waitlist.id }, data: { status: "PUBLISHED" } });
    const joinedAt = new Date(Date.now() - 60_000);
    const firstVisitor = randomUUID();
    const secondVisitor = randomUUID();
    const firstImpression = await db.impression.create({ data: { waitListId: waitlist.id, uniqueUserId: firstVisitor, createdAt: new Date(joinedAt.getTime() - 1_000) } });
    const secondImpression = await db.impression.create({ data: { waitListId: waitlist.id, uniqueUserId: secondVisitor, createdAt: new Date(joinedAt.getTime() - 1_000) } });
    await db.signUp.createMany({ data: [
      { waitListId: waitlist.id, impressionId: firstImpression.id, uniqueUserId: firstVisitor, email: "verified-analytics@example.invalid", emailNormalized: "verified-analytics@example.invalid", createdAt: joinedAt, verifiedAt: joinedAt },
      { waitListId: waitlist.id, impressionId: secondImpression.id, uniqueUserId: secondVisitor, email: "pending-analytics@example.invalid", emailNormalized: "pending-analytics@example.invalid", createdAt: joinedAt },
    ] });
    let wasDark = false;
    try {
      await page.goto(`${base}/wait-lists/${waitlist.id}`);
      await page.getByRole("heading", { name: "Waitlist analytics" }).waitFor();
      await page.locator(".waitlist-analytics-metric").first().waitFor();
      const metrics = await page.locator(".waitlist-analytics-metric").allInnerTexts();
      assert.match(metrics[0], /Visitors\s+2\s+Distinct browsers/);
      assert.match(metrics[1], /Signups\s+2\s+1 verified/);
      assert.match(metrics[2], /Conversion\s+100%/);
      assert.match(metrics[3], /Verification\s+50%\s+1 awaiting verification/);
      assert.deepEqual((await new AxeBuilder({ page }).include(".waitlist-analytics").analyze()).violations, []);
      const rangeResponse = page.waitForResponse((response) => response.url().includes("/analytics?days=7") && response.status() === 200);
      await page.getByRole("button", { name: "7 days" }).click();
      await rangeResponse;
      const tableButton = page.getByRole("button", { name: "Table", exact: true });
      await tableButton.focus();
      await page.keyboard.press("Enter");
      assert.equal(await tableButton.getAttribute("aria-pressed"), "true");
      assert.equal(await page.getByRole("table", { name: /Daily visitors and signups/ }).count(), 1);
      assert.equal(await page.locator(".waitlist-analytics-table-wrap tbody tr").count(), 7);
      assert.deepEqual((await new AxeBuilder({ page }).include(".waitlist-analytics").analyze()).violations, []);
      wasDark = await page.evaluate(() => document.documentElement.classList.contains("dark"));
      await page.evaluate(() => document.documentElement.classList.add("dark"));
      assert.deepEqual((await new AxeBuilder({ page }).include(".waitlist-analytics").analyze()).violations, []);
      await page.setViewportSize({ width: 320, height: 812 });
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await page.screenshot({ path: "/tmp/waitlyze-analytics-mobile.png", fullPage: true });
    } finally {
      await db.signUp.deleteMany({ where: { uniqueUserId: { in: [firstVisitor, secondVisitor] } } });
      await db.impression.deleteMany({ where: { uniqueUserId: { in: [firstVisitor, secondVisitor] } } });
      await db.waitList.update({ where: { id: waitlist.id }, data: { status: "DRAFT" } });
      await page.evaluate((dark) => document.documentElement.classList.toggle("dark", dark), wasDark);
      await page.setViewportSize({ width: 1280, height: 900 });
    }
  });
  await t.test("subscriber tabs resolve flagged referrals with an auditable note", async () => {
    const referrer = await db.signUp.create({ data: { uniqueUserId: randomUUID(), email: "referrer@example.invalid", emailNormalized: "referrer@example.invalid", waitListId: waitlist.id } });
    const invitee = await db.signUp.create({ data: { uniqueUserId: referrer.uniqueUserId, email: "invitee@example.invalid", emailNormalized: "invitee@example.invalid", waitListId: waitlist.id } });
    const referral = await db.referral.create({ data: { signUpId: invitee.id, referredById: referrer.id, reviewStatus: "NEEDS_REVIEW", reviewReason: "same_browser" } });
    await page.goto(`${base}/wait-lists/${waitlist.id}/subscribers`);
    await page.getByRole("button", { name: /Referral review/ }).click();
    await page.getByText("same browser identifier").waitFor();
    await page.getByLabel("Decision note").fill("Confirmed this was a separate invitee.");
    await page.getByRole("button", { name: "Approve credit" }).click();
    await page.getByText("Approved", { exact: true }).waitFor();
    const resolved = await db.referral.findUnique({ where: { id: referral.id } });
    assert.equal(resolved.reviewStatus, "APPROVED");
    assert.equal(resolved.reviewedById, userId);
    assert.equal(resolved.resolution, "Confirmed this was a separate invitee.");
    assert.deepEqual((await new AxeBuilder({ page }).include("[aria-labelledby=referral-review-title]").analyze()).violations, []);
    await db.referral.delete({ where: { id: referral.id } });
    await db.signUp.deleteMany({ where: { id: { in: [referrer.id, invitee.id] } } });
  });
  await t.test("contextual tabs use the selected waitlist and fit a narrow viewport", async () => {
    await page.goto(`${base}/wait-lists/${waitlist.id}`);
    assert.equal(await page.getByRole("heading", { name: "First launch" }).count(), 1);
    assert.deepEqual(await page.getByRole("navigation", { name: "Waitlist sections" }).getByRole("link").allTextContents(), ["Overview", "Page", "Subscribers", "Emails", "Settings"]);
    for (const nestedRoute of ["broadcasts", "automations"]) {
      await page.goto(`${base}/wait-lists/${waitlist.id}/emails/${nestedRoute}`);
      assert.equal(await page.getByRole("navigation", { name: "Waitlist sections" }).getByRole("link", { name: "Emails" }).getAttribute("aria-current"), "page");
    }
    await page.goto(`${base}/wait-lists/${waitlist.id}`);
    for (const width of [320, 375]) {
      await page.setViewportSize({ width, height: 812 });
      await page.goto(`${base}/settings`);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      const settingsSections = page.locator(".product-settings-mobile");
      await settingsSections.locator("summary").click();
      const settingsLinks = settingsSections.getByRole("navigation", { name: "Settings sections" }).getByRole("link");
      assert.deepEqual(await settingsLinks.allTextContents(), ["Profile", "Workspace", "Integrations", "Developers"]);
      const sectionLinkBounds = await settingsLinks.evaluateAll((links) => ({ viewportWidth: innerWidth, links: links.map((link) => {
        const rect = link.getBoundingClientRect();
        return { left: rect.left, right: rect.right, height: rect.height };
      }) }));
      assert.ok(sectionLinkBounds.links.every(({ left, right, height }) => left >= 0 && right <= sectionLinkBounds.viewportWidth && height >= 44));
      await settingsLinks.filter({ hasText: "Integrations" }).click();
      assert.equal(new URL(page.url()).hash, "#integrations");
      await page.getByRole("link", { name: "Skip to content", exact: true }).focus();
      await page.keyboard.press("Enter");
      assert.equal(await page.evaluate(() => document.activeElement.id), "product-content");
      const waitlistsLink = page.getByRole("navigation", { name: "Main navigation" }).getByRole("link", { name: "Waitlists", exact: true });
      await waitlistsLink.focus(); await page.keyboard.press("Enter");
      await page.waitForURL(`${base}/wait-lists`);
      await page.getByRole("heading", { name: "Waitlists", exact: true }).waitFor();
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), JSON.stringify(await page.evaluate(() => [...document.querySelectorAll("body *")].filter((el) => el.getBoundingClientRect().right > innerWidth).slice(0, 8).map((el) => ({ tag: el.tagName, cls: el.className, width: el.getBoundingClientRect().width })))));
      const search = page.getByRole("search");
      await search.getByLabel("Search waitlists").fill("First launch");
      await search.getByRole("button", { name: "Search" }).click();
      await page.waitForURL(`${base}/wait-lists?q=First+launch`);
      assert.equal(await page.getByRole("row", { name: /First launch/ }).count(), 1);
      assert.equal(await page.getByRole("row", { name: /external/ }).count(), 0);
      await page.getByRole("search").getByLabel("Search waitlists").fill("no matching launch");
      await page.getByRole("search").getByRole("button", { name: "Search" }).click();
      await page.getByRole("heading", { name: "No waitlists found" }).waitFor();
      await page.getByRole("link", { name: "Clear search" }).click();
      await page.waitForURL(`${base}/wait-lists`);
      assert.equal(await page.getByRole("row", { name: /First launch/ }).count(), 1);
    }
    await page.goto(`${base}/settings`);
    await page.screenshot({ path: "/tmp/waitlyze-shell-settings-mobile.png", fullPage: true });
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.goto(`${base}/wait-lists`);
    await page.screenshot({ path: "/tmp/waitlyze-shell-waitlists.png", fullPage: true });
  });
  await t.test("launch rehearsal is visible but cannot create real signup or delivery activity", async () => {
    await db.waitList.update({ where: { id: waitlist.id }, data: { templateSnapshot: snapshotTemplate("saas") } });
    const before = { signups: await db.signUp.count({ where: { waitListId: waitlist.id } }), outbox: await db.outboxEvent.count() };
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.goto(`${base}/wait-lists/${waitlist.id}`);
    await page.getByRole("button", { name: "Run check" }).click();
    await page.getByText("Page checks passed").waitFor();
    assert.equal(await db.launchRehearsal.count({ where: { waitListId: waitlist.id } }), 1);
    assert.deepEqual({ signups: await db.signUp.count({ where: { waitListId: waitlist.id } }), outbox: await db.outboxEvent.count() }, before);
    assert.deepEqual((await new AxeBuilder({ page }).include(".launch-rehearsal").analyze()).violations, []);
  });
  await t.test("subscribers filters, profiles, exports, and keyboard flow work across widths", async () => {
    const joinedAt = new Date("2026-09-28T08:00:00.000Z");
    await db.signUp.createMany({ data: [
      { waitListId: waitlist.id, uniqueUserId: randomUUID(), email: "verified-subscriber@example.invalid", createdAt: joinedAt, verifiedAt: joinedAt, city: "Pune", country: "IN", device: "Desktop", ipAddress: "192.0.2.8" },
      { waitListId: waitlist.id, uniqueUserId: randomUUID(), email: "pending-subscriber@example.invalid", createdAt: new Date(joinedAt.getTime() + 1000), city: "Mumbai", country: "IN", device: "Mobile", ipAddress: "192.0.2.9" },
    ] });
    await page.goto(`${base}/wait-lists/${waitlist.id}/subscribers`);
    await page.getByRole("heading", { name: "Subscribers", exact: true }).waitFor();
    await page.getByText(/of 2$/).waitFor();
    await page.getByRole("button", { name: "Verified", exact: true }).click();
    await page.getByText(/of 1$/).waitFor();
    await page.getByRole("button", { name: "verified-subscriber@example.invalid" }).waitFor();
    assert.equal(await page.locator("tbody tr").count(), 1);
    await page.getByRole("button", { name: "Needs confirmation", exact: true }).click();
    await page.getByText(/of 1$/).waitFor();
    await page.getByRole("button", { name: "pending-subscriber@example.invalid" }).waitFor();
    assert.equal(await page.locator("tbody tr").count(), 1);
    await page.getByRole("button", { name: "All subscribers", exact: true }).click();
    await page.getByLabel("Search subscribers by email").fill("verified-subscriber");
    await page.getByText(/of 1$/).waitFor();
    await page.getByRole("button", { name: "verified-subscriber@example.invalid" }).waitFor();
    assert.equal(await page.locator("tbody tr").count(), 1);
    const profileTrigger = page.getByRole("button", { name: "verified-subscriber@example.invalid" });
    await profileTrigger.focus();
    await page.keyboard.press("Enter");
    const profile = page.getByRole("dialog", { name: "Subscriber profile" });
    await profile.waitFor();
    await profile.getByText("Pune, IN", { exact: true }).waitFor();
    await page.keyboard.press("Escape");
    await profile.waitFor({ state: "hidden" });
    assert.equal(await profileTrigger.evaluate((element) => element === document.activeElement), true);
    await page.getByLabel("Search subscribers by email").fill("");
    await page.getByText(/of 2$/).waitFor();
    const downloadPromise = page.waitForEvent("download");
    await page.getByRole("button", { name: "Export CSV" }).click();
    const download = await downloadPromise;
    assert.equal(download.suggestedFilename(), "First launch-subscribers.csv");
    const csv = await readFile(await download.path(), "utf8");
    assert.match(csv, /verified-subscriber@example\.invalid/);
    assert.match(csv, /pending-subscriber@example\.invalid/);
    assert.doesNotMatch(csv, /ipAddress|uniqueUserId/);
    await page.setViewportSize({ width: 320, height: 812 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.deepEqual((await new AxeBuilder({ page }).include(".product-shell").analyze()).violations, []);
    await page.screenshot({ path: "/tmp/waitlyze-subscribers-mobile.png", fullPage: true });
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.screenshot({ path: "/tmp/waitlyze-subscribers-desktop.png", fullPage: true });
  });
  await t.test("workspace selection persists and rejects inaccessible context", async () => {
    const other = await db.workspace.create({ data: { name: "Second workspace", members: { create: { userId, role: "ADMIN" } } } });
    const second = await db.waitList.create({ data: { userId, workspaceId: other.id, name: "Second launch" } });
    await page.goto(`${base}/wait-lists`);
    await page.getByLabel("Workspace", { exact: true }).selectOption(other.id);
    await page.getByRole("button", { name: "Switch", exact: true }).click();
    await page.getByRole("row", { name: /Second launch/ }).waitFor();
    assert.equal(await page.getByRole("row", { name: /First launch/ }).count(), 0);
    await page.reload();
    assert.equal(await page.getByLabel("Workspace", { exact: true }).inputValue(), other.id);
    await page.goto(`${base}/wait-lists/${second.id}/emails`);
    await page.getByLabel("Email Subject").fill("Allowed subject");
    await page.getByRole("button", { name: "Save Template", exact: true }).click();
    await page.getByText("Template saved", { exact: true }).waitFor();
    assert.equal((await db.emailTemplate.findUnique({ where: { waitListId_type: { waitListId: second.id, type: "SIGNUP" } } })).subject, "Allowed subject");
    await db.workspaceMember.update({ where: { workspaceId_userId: { workspaceId: other.id, userId } }, data: { role: "MEMBER" } });
    await page.getByLabel("Email Subject").fill("Denied subject");
    await page.getByRole("button", { name: "Save Template", exact: true }).click();
    await page.getByText("Failed to save template", { exact: true }).waitFor();
    assert.equal((await db.emailTemplate.findUnique({ where: { waitListId_type: { waitListId: second.id, type: "SIGNUP" } } })).subject, "Allowed subject");
    assert.equal((await page.goto(`${base}/wait-lists/${second.id}/emails`)).status(), 404);
    await page.goto(`${base}/wait-lists/${second.id}/edit?buttonText=Member%20CTA`);
    await page.getByRole("button", { name: "Save page", exact: true }).click();
    await page.getByText("Wait list saved successfully", { exact: true }).waitFor();
    assert.equal((await db.waitList.findUnique({ where: { id: second.id } })).buttonText, "Member CTA");
    await page.goto(`${base}/wait-lists/${second.id}/edit?sendEmailsToSubscribers=true`);
    await page.getByRole("button", { name: "Save page", exact: true }).click();
    await page.getByText("Failed to save wait list", { exact: true }).waitFor();
    assert.equal((await db.waitList.findUnique({ where: { id: second.id } })).sendEmailsToSubscribers, false);
    const inaccessible = await page.goto(`${base}/wait-lists/${waitlist.id}`);
    assert.equal(inaccessible.status(), 404);
    await context.addCookies([{ name: "waitlyze-workspace", value: "forged-workspace", domain: "127.0.0.1", path: "/", httpOnly: true, sameSite: "Lax" }]);
    await page.goto(`${base}/wait-lists`);
    assert.equal(await page.getByRole("row", { name: /First launch/ }).count(), 1);
    assert.equal(await page.getByRole("row", { name: /Second launch/ }).count(), 0);
  });
  await t.test("creation assigns the selected personal workspace and navigates immediately", async () => {
    await context.addCookies([{ name: "waitlyze-workspace", value: personal.id, domain: "127.0.0.1", path: "/", httpOnly: true, sameSite: "Lax" }]);
    await page.goto(`${base}/wait-lists/new`);
    await page.getByRole("radio", { name: /Mobile app/ }).check();
    await page.setViewportSize({ width: 320, height: 812 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    const mobileWizardAction = page.locator(".product-create-actions");
    assert.equal(await mobileWizardAction.evaluate((element) => getComputedStyle(element).position), "sticky");
    const continueButton = page.getByRole("button", { name: "Continue with Mobile app" });
    const actionBounds = await continueButton.boundingBox();
    assert.ok(actionBounds && actionBounds.y >= 0 && actionBounds.y + actionBounds.height <= 812, "the primary wizard action remains in the mobile viewport");
    const preview = page.locator(".product-template-preview");
    await preview.scrollIntoViewIfNeeded();
    await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
    const [previewBounds, scrolledActionBounds] = await Promise.all([
      preview.boundingBox(),
      continueButton.boundingBox(),
    ]);
    assert.ok(previewBounds && scrolledActionBounds && previewBounds.y + previewBounds.height <= scrolledActionBounds.y, "the sticky action does not cover the end of the template preview");
    assert.ok(scrolledActionBounds && scrolledActionBounds.y >= 0 && scrolledActionBounds.y + scrolledActionBounds.height <= 812, "the primary wizard action remains reachable at the end of the preview");
    assert.deepEqual((await new AxeBuilder({ page }).include(".product-shell").analyze()).violations, []);
    await page.screenshot({ path: "/tmp/waitlyze-template-mobile.png", fullPage: true });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.screenshot({ path: "/tmp/waitlyze-template-desktop.png", fullPage: true });
    await continueButton.focus();
    await page.keyboard.press("Enter");
    const detailsHeading = page.getByRole("heading", { name: "Add details", exact: true });
    assert.equal(await detailsHeading.evaluate((element) => document.activeElement === element), true);
    assert.equal(await detailsHeading.evaluate((element) => getComputedStyle(element).outlineWidth), "2px");
    await page.getByLabel("Waitlist name", { exact: true }).fill("Created fixture");
    await page.getByLabel("Page address", { exact: true }).fill(`fixture-${randomUUID()}`);
    await page.reload();
    await page.getByRole("button", { name: "Continue with Mobile app" }).click();
    assert.equal(await page.getByLabel("Waitlist name", { exact: true }).inputValue(), "Created fixture");
    await page.getByRole("button", { name: "Review draft" }).click();
    await page.getByRole("button", { name: "Back", exact: true }).click();
    assert.equal(await page.getByLabel("Waitlist name", { exact: true }).inputValue(), "Created fixture");
    await page.getByRole("button", { name: "Review draft" }).click();
    await page.getByRole("button", { name: "Create draft", exact: true }).click();
    await page.waitForURL(/\/wait-lists\/[^/]+\/edit$/);
    await page.getByRole("heading", { name: "Page", exact: true }).waitFor();
    assert.equal(await page.getByLabel("Headline", { exact: true }).inputValue(), "Something new for your everyday.");
    const initialDraft = await db.waitList.findFirst({ where: { userId, name: "Created fixture" } });
    assert.equal(initialDraft.templateRevision, 1);
    await page.goto(`${base}/wait-lists/${initialDraft.id}`);
    const readiness = page.getByRole("region", { name: "Launch readiness" });
    await readiness.waitFor({ state: "visible" });
    await readiness.getByText("Your saved page matches the template requirements.").waitFor({ state: "visible" });
    await readiness.getByText("One valid email signup form is configured.").waitFor({ state: "visible" });
    await readiness.getByText("Drafts stay private until you publish them.").waitFor({ state: "visible" });
    const review = readiness.getByRole("link", { name: "Review Publish your waitlist", exact: true });
    assert.equal(await review.getAttribute("href"), `/wait-lists/${initialDraft.id}/edit`);
    await page.setViewportSize({ width: 320, height: 812 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.deepEqual((await new AxeBuilder({ page }).include(".launch-readiness").analyze()).violations, []);
    await page.setViewportSize({ width: 1280, height: 900 });
    let reachedByKeyboard = false;
    for (let tab = 0; tab < 24 && !reachedByKeyboard; tab += 1) {
      await page.keyboard.press("Tab");
      reachedByKeyboard = await review.evaluate((element) => document.activeElement === element);
    }
    assert.equal(reachedByKeyboard, true);
    assert.equal(await review.evaluate((element) => element.matches(":focus-visible")), true);
    assert.equal(await review.evaluate((element) => getComputedStyle(element).outlineWidth), "2px");
    await page.keyboard.press("Enter");
    await page.waitForURL(new RegExp(`/wait-lists/${initialDraft.id}/edit$`));
    await page.getByLabel("Headline", { exact: true }).fill("  A better way to make it happen.  ");
    await page.getByText("Saved · version 2").waitFor({ state: "visible", timeoutMs: 10000 });
    assert.equal(await page.getByLabel("Headline", { exact: true }).inputValue(), "  A better way to make it happen.  ");
    assert.equal((await db.waitList.findUnique({ where: { id: initialDraft.id } })).templateSnapshot.sections[0].heading, "  A better way to make it happen.  ");
    await page.getByRole("button", { name: "Undo last change" }).click();
    await page.getByText("Saved · version 3").waitFor({ state: "visible", timeoutMs: 10000 });
    assert.equal((await db.waitList.findUnique({ where: { id: initialDraft.id } })).templateSnapshot.sections[0].heading, "Something new for your everyday.");
    const concurrentPage = await context.newPage();
    await concurrentPage.goto(`${base}/wait-lists/${initialDraft.id}/edit`);
    await concurrentPage.getByLabel("Headline", { exact: true }).waitFor({ state: "visible" });
    await page.getByLabel("Headline", { exact: true }).fill("Saved in the first tab");
    await page.getByText("Saved · version 4").waitFor({ state: "visible", timeoutMs: 10000 });
    assert.equal((await db.waitList.findUnique({ where: { id: initialDraft.id } })).templateSnapshot.sections[0].heading, "Saved in the first tab");
    await concurrentPage.getByLabel("Introduction", { exact: true }).fill("Saved from the other tab.");
    await concurrentPage.getByRole("alert").getByText(/newer page version/).waitFor({ state: "visible", timeoutMs: 10000 });
    await concurrentPage.getByRole("button", { name: "Replace saved version with mine" }).click();
    await concurrentPage.getByText("Saved · version 5").waitFor({ state: "visible", timeoutMs: 10000 });
    const recoveredDraft = await db.waitList.findUnique({ where: { id: initialDraft.id } });
    assert.equal(recoveredDraft.templateSnapshot.sections[0].heading, "Something new for your everyday.");
    assert.equal(recoveredDraft.templateSnapshot.sections[0].body, "Saved from the other tab.");
    await concurrentPage.reload();
    assert.equal(await concurrentPage.getByLabel("Introduction", { exact: true }).inputValue(), "Saved from the other tab.");
    assert.equal(await concurrentPage.getByRole("button", { name: "Save now" }).isEnabled(), false);
    const headline = concurrentPage.getByLabel("Headline", { exact: true });
    await headline.fill("Local page edit");
    const introduction = concurrentPage.getByLabel("Introduction", { exact: true });
    await introduction.pressSequentially(" extra text");
    await introduction.press("Control+z");
    assert.equal(await headline.inputValue(), "Local page edit");
    await concurrentPage.close();
    await page.setViewportSize({ width: 320, height: 812 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.deepEqual((await new AxeBuilder({ page }).include(".product-shell").analyze()).violations, []);
    await page.setViewportSize({ width: 1280, height: 900 });
    const created = await db.waitList.findFirst({ where: { userId, name: "Created fixture" } });
    assert.ok(created);
    assert.equal(created.workspaceId, personal.id);
    assert.equal(created.status, "DRAFT");
    assert.equal(created.templateSnapshot.templateId, "mobile");
    const publicResponse = await fetch(`${base}/forms/${created.id}`);
    assert.equal(publicResponse.status, 404);
    assert.equal((await publicResponse.text()).includes("Created fixture"), false);
    for (const route of ["sign_up", "impressions"]) {
      const response = await fetch(`${base}/api/v1/${route}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ waitListId: created.id, email: "visitor@example.invalid", hypeSession: randomUUID() }) });
      assert.equal(response.status, 400);
    }
    assert.equal(await db.signUp.count({ where: { waitListId: created.id } }), 0);
    assert.equal(await db.impression.count({ where: { waitListId: created.id } }), 0);
  });
  await t.test("deletion needs typed confirmation and returns to the list", async () => {
    await page.goto(`${base}/wait-lists/${waitlist.id}/settings`);
    await page.getByRole("button", { name: "Delete waitlist", exact: true }).click();
    assert.equal(await page.getByRole("button", { name: "Permanently delete" }).isEnabled(), false);
    await page.getByRole("button", { name: "Cancel", exact: true }).click();
    await page.getByRole("dialog").waitFor({ state: "hidden" });
    assert.ok(await db.waitList.findUnique({ where: { id: waitlist.id } }));
    await page.getByRole("button", { name: "Delete waitlist", exact: true }).click();
    await page.getByLabel('Type “First launch” to confirm').fill("First launch");
    await page.getByRole("button", { name: "Permanently delete" }).click();
    await page.waitForURL(`${base}/wait-lists`);
    assert.equal(await db.waitList.findUnique({ where: { id: waitlist.id } }), null);
  });
  assert.deepEqual(errors, []);
});
