import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { once } from "node:events";
import { chromium } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { PrismaClient } from "../../src/generated/prisma/client.ts";
import { PrismaPg } from "@prisma/adapter-pg";
import { workspaceTestTarget } from "../../scripts/workspace-test-target.mjs";
import { createWorkspaceService } from "../../src/lib/workspaces/service.mjs";
import { startFixtureServer, signedCookie } from "../support/http-fixture.mjs";

const target = workspaceTestTarget(process.env.WORKSPACE_TEST_DATABASE_URL);
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: target }) });
const service = createWorkspaceService(db);
const base = "http://127.0.0.1:3100";

test("authenticated two-destination shell uses real workspace data", async (t) => {
  const userId = `fixture-${randomUUID()}`;
  let server, browser;
  t.after(async () => {
    await browser?.close();
    if (server?.exitCode === null) { server.kill("SIGTERM"); await once(server, "exit"); }
    await db.waitList.deleteMany({ where: { userId } });
    await db.workspace.deleteMany({ where: { members: { some: { userId } } } });
    await db.user.deleteMany({ where: { id: userId } });
    await db.$disconnect();
  });
  await db.user.create({ data: { id: userId, email: `${userId}@example.invalid`, name: "Shell fixture" } });
  const token = randomUUID();
  await db.session.create({ data: { id: randomUUID(), token, userId, expiresAt: new Date(Date.now() + 120000) } });
  const personal = await service.ensurePersonal(userId);
  const waitlist = await db.waitList.create({ data: { userId, workspaceId: personal.id, name: "First launch", description: "Real fixture content" } });
  server = await startFixtureServer();
  browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const cookie = signedCookie(token).split("=");
  await context.addCookies([{ name: cookie[0], value: cookie[1], domain: "127.0.0.1", path: "/", httpOnly: true, sameSite: "Lax" }]);
  const page = await context.newPage();
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await t.test("dashboard redirects and navigation has exactly two real destinations", async () => {
    await page.goto(`${base}/dashboard`);
    assert.ok(page.url().endsWith("/wait-lists"));
    assert.deepEqual(await page.getByRole("navigation", { name: "Main navigation" }).getByRole("link").allTextContents(), ["Waitlists", "Settings"]);
    assert.equal(await page.locator("aside").count(), 0);
    assert.equal(await page.getByRole("row", { name: /First launch/ }).count(), 1);
    assert.equal(await page.getByLabel("Workspace", { exact: true }).count(), 0);
  });
  await t.test("profile saves on the real account and settings passes axe", async () => {
    await page.getByRole("link", { name: "Settings", exact: true }).click();
    await page.getByLabel("Display name").fill("Updated fixture");
    await page.getByRole("button", { name: "Save profile" }).click();
    await page.getByRole("status").filter({ hasText: "Profile saved." }).waitFor();
    assert.equal((await db.user.findUnique({ where: { id: userId } })).name, "Updated fixture");
    await page.reload();
    assert.equal(await page.getByLabel("Display name").inputValue(), "Updated fixture");
    await page.getByLabel("Display name").fill("   ");
    await page.getByRole("button", { name: "Save profile" }).click();
    await page.getByRole("alert").filter({ hasText: "Enter a name" }).waitFor();
    assert.equal(await page.getByLabel("Display name").inputValue(), "   ");
    await page.getByLabel("Display name").fill("Updated fixture");
    assert.deepEqual((await new AxeBuilder({ page }).include(".product-shell").analyze()).violations, []);
  });
  await t.test("contextual tabs use the selected waitlist and fit a narrow viewport", async () => {
    await page.goto(`${base}/wait-lists/${waitlist.id}`);
    assert.equal(await page.getByRole("heading", { name: "First launch" }).count(), 1);
    assert.deepEqual(await page.getByRole("navigation", { name: "Waitlist sections" }).getByRole("link").allTextContents(), ["Overview", "Page", "Subscribers", "Emails", "Settings"]);
    for (const width of [320, 375]) {
      await page.setViewportSize({ width, height: 812 });
      await page.goto(`${base}/settings`);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await page.getByRole("link", { name: "Skip to content", exact: true }).focus();
      await page.keyboard.press("Enter");
      assert.equal(await page.evaluate(() => document.activeElement.id), "product-content");
      const waitlistsLink = page.getByRole("navigation", { name: "Main navigation" }).getByRole("link", { name: "Waitlists", exact: true });
      await waitlistsLink.focus(); await page.keyboard.press("Enter");
      await page.waitForURL(`${base}/wait-lists`);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    }
    await page.goto(`${base}/settings`);
    await page.screenshot({ path: "/tmp/waitlyze-shell-settings-mobile.png", fullPage: true });
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.goto(`${base}/wait-lists`);
    await page.screenshot({ path: "/tmp/waitlyze-shell-waitlists.png", fullPage: true });
  });
  await t.test("workspace selection persists and rejects inaccessible context", async () => {
    const other = await db.workspace.create({ data: { name: "Second workspace", members: { create: { userId, role: "ADMIN" } } } });
    const second = await db.waitList.create({ data: { userId, workspaceId: other.id, name: "Second launch" } });
    await page.goto(`${base}/wait-lists`);
    await page.getByLabel("Workspace", { exact: true }).selectOption(other.id);
    await page.getByRole("button", { name: "Switch", exact: true }).click();
    await page.getByRole("row", { name: /Second launch/ }).waitFor();
    assert.equal(await page.getByRole("row", { name: /First launch/ }).count(), 0);
    await page.reload();
    assert.equal(await page.getByLabel("Workspace", { exact: true }).inputValue(), other.id);
    await page.goto(`${base}/wait-lists/${second.id}/emails`);
    await page.getByLabel("Email Subject").fill("Allowed subject");
    await page.getByRole("button", { name: "Save Template", exact: true }).click();
    await page.getByText("Template saved", { exact: true }).waitFor();
    assert.equal((await db.emailTemplate.findUnique({ where: { waitListId_type: { waitListId: second.id, type: "SIGNUP" } } })).subject, "Allowed subject");
    await db.workspaceMember.update({ where: { workspaceId_userId: { workspaceId: other.id, userId } }, data: { role: "MEMBER" } });
    await page.getByLabel("Email Subject").fill("Denied subject");
    await page.getByRole("button", { name: "Save Template", exact: true }).click();
    await page.getByText("Failed to save template", { exact: true }).waitFor();
    assert.equal((await db.emailTemplate.findUnique({ where: { waitListId_type: { waitListId: second.id, type: "SIGNUP" } } })).subject, "Allowed subject");
    assert.equal((await page.goto(`${base}/wait-lists/${second.id}/emails`)).status(), 404);
    await page.goto(`${base}/wait-lists/${second.id}/edit?buttonText=Member%20CTA`);
    await page.getByRole("button", { name: "Save page", exact: true }).click();
    await page.getByText("Wait list saved successfully", { exact: true }).waitFor();
    assert.equal((await db.waitList.findUnique({ where: { id: second.id } })).buttonText, "Member CTA");
    await page.goto(`${base}/wait-lists/${second.id}/edit?sendEmailsToSubscribers=true`);
    await page.getByRole("button", { name: "Save page", exact: true }).click();
    await page.getByText("Failed to save wait list", { exact: true }).waitFor();
    assert.equal((await db.waitList.findUnique({ where: { id: second.id } })).sendEmailsToSubscribers, false);
    const inaccessible = await page.goto(`${base}/wait-lists/${waitlist.id}`);
    assert.equal(inaccessible.status(), 404);
    await context.addCookies([{ name: "waitlyze-workspace", value: "forged-workspace", domain: "127.0.0.1", path: "/", httpOnly: true, sameSite: "Lax" }]);
    await page.goto(`${base}/wait-lists`);
    assert.equal(await page.getByRole("row", { name: /First launch/ }).count(), 1);
    assert.equal(await page.getByRole("row", { name: /Second launch/ }).count(), 0);
  });
  await t.test("creation assigns the selected personal workspace and navigates immediately", async () => {
    await context.addCookies([{ name: "waitlyze-workspace", value: personal.id, domain: "127.0.0.1", path: "/", httpOnly: true, sameSite: "Lax" }]);
    await page.goto(`${base}/wait-lists/new`);
    await page.getByLabel("Waitlist Name", { exact: true }).fill("Created fixture");
    await page.getByRole("button", { name: /Create.*Waitlist/i }).click();
    await page.waitForURL(/\/wait-lists\/[^/]+\/edit$/);
    const created = await db.waitList.findFirst({ where: { userId, name: "Created fixture" } });
    assert.ok(created);
    assert.equal(created.workspaceId, personal.id);
  });
  await t.test("deletion needs typed confirmation and returns to the list", async () => {
    await page.goto(`${base}/wait-lists/${waitlist.id}/settings`);
    await page.getByRole("button", { name: "Delete waitlist", exact: true }).click();
    assert.equal(await page.getByRole("button", { name: "Permanently delete" }).isEnabled(), false);
    await page.getByRole("button", { name: "Cancel", exact: true }).click();
    assert.ok(await db.waitList.findUnique({ where: { id: waitlist.id } }));
    await page.getByRole("button", { name: "Delete waitlist", exact: true }).click();
    await page.getByLabel('Type “First launch” to confirm').fill("First launch");
    await page.getByRole("button", { name: "Permanently delete" }).click();
    await page.waitForURL(`${base}/wait-lists`);
    assert.equal(await db.waitList.findUnique({ where: { id: waitlist.id } }), null);
  });
  assert.deepEqual(errors, []);
});
